# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 01:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200, verbose_name='Short Description')),
                ('details', models.CharField(max_length=600, verbose_name='Details')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping_time', models.DecimalField(decimal_places=2, help_text='Maximum shipping time after order is made', max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Shipping Time')),
                ('other_features', models.CharField(blank=True, max_length=600, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
