# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 05:14
from __future__ import unicode_literals

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shipping_time',
        ),
        migrations.AddField(
            model_name='item',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2017, 3, 17), verbose_name='Expected Delivery Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='image1',
            field=models.ImageField(upload_to=app.models.generate_image_name),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.generate_image_name),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.generate_image_name),
        ),
        migrations.AlterField(
            model_name='item',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.generate_image_name),
        ),
    ]
